### ISSUE TITLE
Routing tutorial recommends using encodeURIComponent for HTML

### ISSUE THREAD

**Issue by imgx64** [hapijs/hapi.dev#128]
In the [Routing tutorial](https://hapi.dev/tutorials/routing/), `encodeURIComponent` is used 6 times (including two typos of `encodeURLComponent`) to escape **HTML**. This is wrong because it replaces characters with percent-encoding (for example, space is replaced with `%20`), which won't be displayed correctly as HTML.

There are two ways to fix this:
1. Remove `encodeURIComponent` and set Content-Type to `text/plain`. So the first example would become:

       return h.response(`Hello ${request.params.user}!`).type('text/plain');

2. Recommend `Hoek.escapeHtml` instead. So the first example would become:

       return `Hello ${Hoek.escapeHtml(request.params.user)}!`;

I don't know which one is better for a tutorial about routing, so I opened this issue instead of submitting a PR.

**Comment by jarrodyellets** [comment]
Sounds good, I'll take care of it
