### ISSUE TITLE
Invalid coding convention at 'Getting Started' tutorial

### ISSUE THREAD

**Issue by ghkim3221** [hapijs/hapi.dev#155]
Hi,
I found an invalid coding convention at 'Getting Started' tutorial's '[Adding Routes](https://github.com/hapijs/hapi.dev/blob/master/static/lib/tutorials/en_US/gettingStarted.md#-adding-routes)' section.
There is no whitespace at `path:'/',`.

Thank you.

**Comment by Nargonath** [comment]
Thanks @ghkim3221. Do you want to submit a PR for that?

**Comment by ghkim3221** [comment]
Thank you. I requested #156.
