### ISSUE TITLE
Update Slack invite link

### ISSUE THREAD

**Issue by jarrodyellets** [hapijs/hapi.dev#188]
The Slack invite link has expired.

**Comment by hueniverse** [comment]
The link is set to never expire. Make sure it is this:

https://join.slack.com/t/hapihour/shared_invite/enQtNTA5MDUzOTAzOTU4LTY1YzY0ZDM4YTZkNzYzOGExNDYzZjQ3YzJkNTVhNmExMDdlMjY3NDhkNDUxNjU4NTY1YjkzMTcxMzBkMzFiNWE
