### ISSUE TITLE
the https://hapi.dev website is down

### ISSUE THREAD

**Issue by adrian-gierakowski** [hapijs/hapi.dev#237]
#### Support plan

* *which support plan is this issue covered by?* (e.g. Community, Core, Plus, or Enterprise): 
* *is this issue currently blocking your project?* (yes/no):
* *is this issue affecting a production system?* (yes/no):

#### Context

* *node version*: 
* *module version with issue*: 
* *last module version without issue*: 
* *environment* (e.g. node, browser, native): 
* *used with* (e.g. hapi application, another framework, standalone, ...):
* *any other relevant information*:

#### What are you trying to achieve or the steps to reproduce?

```js
const some = 'properly formatted code example';
```

**Comment by Marsup** [comment]
No it's not.

**Comment by adrian-gierakowski** [comment]
yeah, just realised that it loads on my phone

but it does not on my Mac, neither Chrome nor Safari 
would you have any ideas why that could be? I haven't noticed this for any other site

**Comment by Marsup** [comment]
Do you have any actionable error?

**Comment by adrian-gierakowski** [comment]
wow, it looks like I can't load any `.dev` domains on my Mac

**Comment by adrian-gierakowski** [comment]
no, nothing actionable on your side

**Comment by Marsup** [comment]
Reminds me of some software that used *.dev to route local dev to whatever server you're running locally.

**Comment by adrian-gierakowski** [comment]
for anyone who encounters the same issue, it was due to the fact that I once used Pow. Here's how to fix it:
https://stackoverflow.com/questions/28199785/why-all-dev-domains-target-to-my-localhost/55223730#55223730

@Marsup sorry for the noise
