### ISSUE TITLE
In the labs API documentation, reorganize `script.test` to make Flags subsection more apparent?

### ISSUE THREAD

**Issue by zemccartney** [hapijs/hapi.dev#243]
#### Context

https://hapi.dev/family/lab/?v=22.0.2

* *node version*: N/A (issue pertains to formatting of documentation at hapi.dev)
* *module version*: 22.0.2

#### What are you trying to achieve or the steps to reproduce ?

First off, apologies if this issue is better filed directly on the `labs` repo. I filed here because I observed the issue on the site; happy to relocate this issue if you believe it's relevant.

On reading through the `lab` documentation the other day, I found it a bit unexpected that the "Flags" subsection appears nested under `script.test.skip`, given that flags are used by all variants of the `script.test` method (e.g. plain, `skip`, and `only`). Do y'all think it would be beneficial to somehow relocate the flags section to make that feature more apparent?

A couple of ideas:

- Move the "Flags" subsection to the same header level as the other children of the "Methods" section i.e. on the same level as `script.test.skip`, instead of nested within it

- Make `script.test` its own section; nest `script.test.only`, `script.test.skip`, and `Flags` under `script.test`

So, the docs would look like:

```
-- script.test
    |-- Flags
    |-- only()
    |-- skip()
```

To be clear, not a big deal at all, of course, just something that for whatever reason didn't sync with my brain :)
Thanks for all the hard work on the site and on this great community in general! Viva hapi!

**Comment by hueniverse** [comment]
It's all auto generated from the lab API.md file so best to open the issue there or better yet submit a PR that shows what your proposal is.

**Comment by zemccartney** [comment]
Ay, sorry for my delayed response. But cool, that sounds good, I'll take a shot at that. Thanks!
