### ISSUE TITLE
Usage of qs in routing tutorial does not work

### ISSUE THREAD

**Issue by tundebabzy** [hapijs/hapi.dev#297]
#### Context
https://hapi.dev/tutorials/routing/?lang=en_US#query
* *node version*: NA
* *module version*: https://hapi.dev/tutorials/routing/?lang=en_US#query

#### What are you trying to achieve or the steps to reproduce ?
It seems like the documentation for using `qs` when dealing with complex query parameters might be wrong. The documentation has this:
```js
const Hapi = require('@hapi/hapi');
const Qs = require('qs');

const server = Hapi.server({
    port: 3000,
    host: 'localhost',
    query: {
        parser: (query) => Qs.parse(query)
    }
});
...
```
Unsurprisingly, I discovered this didn't work as `Qs.parse` expects a string and from my understanding of hapi, `request.query` should be an Object [See ](https://hapi.dev/api/?v=19.1.1#-serveroptionsqueryparser).

Am I missing some details?

**Comment by Marsup** [comment]
Confirmed, but that's likely a bug in hapi, not in the documentation.

**Comment by tundebabzy** [comment]
I thought so too but I wanted to confirm. I will open an issue in hapi. Thanks for your quick reply.
