### ISSUE TITLE
ERR_FAILED https://hapi.dev/

### ISSUE THREAD

**Issue by mahnunchik** [hapijs/hapi.dev#308]
https://hapi.dev/ website couldn't be opened.

```js
Uncaught (in promise) no-response: no-response :: [{"url":"https://hapi.dev/"}]
    at a.makeRequest (https://cdn.jsdelivr.net/npm/workbox-cdn@4.3.1/workbox/workbox-strategies.prod.js:1:2145)
```

#### Context

Latest Chrome and FF

#### What are you trying to achieve or the steps to reproduce?

Open https://hapi.dev/

#### What was the result you got?

Working website.

#### What result did you expect?

ERR_FAILED

**Comment by mahnunchik** [comment]
`Network -> Disable cache` helps for some time.

**Comment by mahnunchik** [comment]
https://hapi.dev/family?sort=alphabetical

ERR_FAILED

```js
The FetchEvent for "https://hapi.dev/family?sort=alphabetical" resulted in a network error response: the promise was rejected.
workbox-strategies.prod.js:1 Uncaught (in promise) no-response: no-response :: [{"url":"https://hapi.dev/family?sort=alphabetical"}]
    at a.makeRequest (https://cdn.jsdelivr.net/npm/workbox-cdn@4.3.1/workbox/workbox-strategies.prod.js:1:2145)
The FetchEvent for "https://hapi.dev/family?sort=alphabetical" resulted in a network error response: the promise was rejected.
workbox-strategies.prod.js:1 Uncaught (in promise) no-response: no-response :: [{"url":"https://hapi.dev/family?sort=alphabetical"}]
    at a.makeRequest (https://cdn.jsdelivr.net/npm/workbox-cdn@4.3.1/workbox/workbox-strategies.prod.js:1:2145)
```

**Comment by jarrodyellets** [comment]
That is an ongoing, intermittent Nuxt PWA issue.  See the following:

https://github.com/nuxt-community/pwa-module/issues/176

I've made some adjustments, let me know if you see an improvement.  I also adjusted the module href, so that should fix your second issue.

**Comment by keerthivasan-r** [comment]
I guess its working now. Is the problem fixed now?

**Comment by lloydbenson** [comment]
I couldn't see this problem but please let us know if this is resolved now. If I don't see it closed out by you and no response soon, I will close up this issue assuming that @jarrodyellets did resolve it. Thanks for reporting the issue and thanks @jarrodyellets for the potential fixes!

**Comment by lloydbenson** [comment]
Closing this up.
