### ISSUE TITLE
Continuously declared headers do not break line

### ISSUE THREAD

**Issue by jonathansamines** [hapijs/hapi.dev#329]
#### Support plan

* *which support plan is this issue covered by?* (e.g. Community, Core, Plus, or Enterprise): Community
* *is this issue currently blocking your project?* (yes/no): No
* *is this issue affecting a production system?* (yes/no): No

#### Context

* *node version*: -
* *module version with issue*: -
* *last module version without issue*: -
* *environment* (e.g. node, browser, native): Chrome browser
* *used with* (e.g. hapi application, another framework, standalone, ...): -
* *any other relevant information*: -

#### What are you trying to achieve or the steps to reproduce?
Whenever there are headers declared one after the other, they are rendered on the same line instead of multiple lines

<img width="1677" alt="image" src="https://user-images.githubusercontent.com/1268268/77036206-2f5d7c00-6974-11ea-8a70-4c78aede03ca.png">

I think it might be caused because headers are declared with `inline-block` display, instead of `block`

#### What was the result you got?
Continuously declared headers are rendered in the same line

#### What result did you expect?
Continuously declared headers are rendered in different lines

**Comment by jarrodyellets** [comment]
Fixed with #330
