### ISSUE TITLE
Vision API navigation is broken

### ISSUE THREAD

**Issue by jameswragg** [hapijs/hapi.dev#337]
#### Context

* *node version*: v12.13.0
* *module version*: latest

#### What are you trying to achieve or the steps to reproduce ?

The markdown used in Vision's API.md file is not being parsed correctly on the hapi.dev site.
See: https://hapi.dev/module/vision/api/ and notice the sidebar nav broken.

The offending markdown seems to be in the following file, I imagine its the link in the header: https://raw.githubusercontent.com/hapijs/vision/master/API.md

```
## The `view` [handler](https://github.com/hapijs/hapi/blob/master/API.md#serverdecoratetype-property-method-options)
```

**Comment by jarrodyellets** [comment]
I adjusted the API, so its good to go now.

**Comment by jameswragg** [comment]
Thanks for fixing up the markdown. I'm noticing the nav is still broken on https://hapi.dev/module/vision/api/ is this a cache issue or is it needing a redeploy?

**Comment by jarrodyellets** [comment]
Looks like it was a deployment issue...should be working now.  Let me know if it's still causing problems.
