### ISSUE TITLE
Documentation headers lack `id` attribute

### ISSUE THREAD

**Issue by stevendesu** [hapijs/hapi.dev#338]
#### Support plan

* *which support plan is this issue covered by?* (e.g. Community, Core, Plus, or Enterprise): Community
* *is this issue currently blocking your project?* (yes/no): no
* *is this issue affecting a production system?* (yes/no): no

#### Context

* *node version*: v13.11.0 (irrelevant, though)
* *module version with issue*: Commit 2dee2b6522b63e07f0084ea652c39828502ec413 (hapi.dev has no release numbers listed in GitHub)
* *last module version without issue*: Don't know (see below)
* *environment* (e.g. node, browser, native): browser
* *used with* (e.g. hapi application, another framework, standalone, ...): standalone
* *any other relevant information*:

I clicked back through some very old commits (such as cdc0a5d7c3db423af18510edd3be9815c0bb345b) in an attempt to binary search for the start of the problem and noticed a few things:

 1. Older versions of the documentation had a table of contents at the top that was removed at some point (possibly because it didn't work?)
 2. Documentation is generated from Markdown files, so whatever tool is performing the generation is failing to place the `id` attribute
 3. All of the headers possessed a starting `<a>` tag before the actual header name -- this could be what's tripping up the Markdown generation? (just a thought, can't say for certain)

#### What are you trying to achieve or the steps to reproduce?

```js
// No relevant code (code block left in case a template scanning bot would otherwise invalidate my bug report)
```

I'm attempting to copy a section link from the hapi.dev documentation to share with my team, using this icon:

![Screen Shot 2020-03-27 at 10 59 42 AM](https://user-images.githubusercontent.com/1384974/77770278-60e0e200-701b-11ea-8bb1-8050054610d3.png)

#### What was the result you got?

The following link was copied to my clipboard:

https://hapi.dev/tutorials/auth/?lang=en_US#

Directing someone to this link loads the page but does not scroll to the appropriate section

#### What result did you expect?

A link similar to the following:

https://hapi.dev/tutorials/auth/?lang=en_US#basic

When such a link is clicked, I would expect it to load the page **and** scroll to the appropriate section

**Comment by jarrodyellets** [comment]
Fixed with #340
