### ISSUE TITLE
Expanding submenu items breaks menu item selection

### ISSUE THREAD

**Issue by thomasmichaelwallace** [hapijs/hapi.dev#341]
#### Support plan

* *which support plan is this issue covered by?* Community 
* *is this issue currently blocking your project?* no
* *is this issue affecting a production system?* no

#### Context

* *node version*: 12.16.1
* *module version with issue*: 1.0.0
* *last module version without issue*: unknown
* *environment* (e.g. node, browser, native): https://hapi.dev, and local browser
* *used with* (e.g. hapi application, another framework, standalone, ...): standalone
* *any other relevant information*:
  * this happens on your production site (https://hapi.dev) and I can reproduce it building `master` on this repo.
  * I have tried this with Firefox 75.0b10 (developer edition) and Safari (13.0.5) both on MacOS (10.15.3)

#### What are you trying to achieve or the steps to reproduce?

In the module help, (for example https://hapi.dev/module/joi/api/?v=17.1.1) if you expand a submenu then future mouse clicks are offset vertically, so that when you later try to click something, it actually selects the item a few sections above it.

#### What was the result you got?

Clicking items selects the wrong thing, I've included this gif capturing the whole experience (http://g.recordit.co/WvMy52Psab.gif):

![WvMy52Psab](https://user-images.githubusercontent.com/1954845/77895881-5454c780-726f-11ea-8b89-f3f67d5ee1f3.gif)

#### What result did you expect?

I expected to be able to expand/contract submenu items and continue to be able to precisely pick the document I wanted to see.

This is making working with Joi quite hard! Thanks for all the work so far, please let me know what else I can provide to help solve this issue!

All the best.

**Comment by jarrodyellets** [comment]
Fixed with #342

**Comment by thomasmichaelwallace** [comment]
Awesome - thanks for quick response.
