### ISSUE TITLE
Documentation links for many modules are broken

### ISSUE THREAD

**Issue by namco1992** [hapijs/hapi.dev#380]
#### Context

* *node version*: 12.18.2
* *module version*: 19.1.1 

#### What are you trying to achieve or the steps to reproduce ?

The documentation links for many modules are broken. For example: https://hapi.dev/module/joi is 404 now, together with many others.

**Comment by lloydbenson** [comment]
@namco1992: there isn't alot of detail here on the source but it I believe I likely fixed it with this [commit](https://github.com/hapijs/hapi.dev/commit/40afc187e0e7b3a14f2bf3044e6debde36498ea0). Please confirm if this addresses the issue or if you can let me know where that link specifically is referenced, more details would be helpful. For joi documentation specifically, the joi module moved to https://github.com/sideway/joi.

**Comment by namco1992** [comment]
Hello @lloydbenson, I believe it's related to https://github.com/sideway/joi/issues/2437#issuecomment-671370527 and your comment on that issue answered the question. Thank you very much!
