### ISSUE TITLE
Investigate a potential error in Joi api link

### ISSUE THREAD

**Issue by Nargonath** [hapijs/hapi.dev#414]
#### Support plan

* *is this issue currently blocking your project?* (yes/no): no
* *is this issue affecting a production system?* (yes/no): no

#### Context

* *node version*: 
* *module version with issue*: 
* *last module version without issue*: 
* *environment* (e.g. node, browser, native): 
* *used with* (e.g. hapi application, another framework, standalone, ...):
* *any other relevant information*: someone raised the problem in Slack about the Joi api section raising errors.

#### What are you trying to achieve or the steps to reproduce?

Here the person's message:

> Hey guys, I’m not sure if this is the best forum, but it looks like http://hapi.dev/module/joi/api is currently broken in “production.” I’m assuming the issue is that when Eran moved Joi, it’s 404ing because the code can no longer find this module?

#### What was the result you got?

Here is a screenshot he provided:
![image](https://user-images.githubusercontent.com/583657/96094531-bf917e80-0ecd-11eb-82af-ab20f3f17ab6.png)

#### What result did you expect?

No errors. I believe we already handled Joi departure on the website so this might be a regression.

**Comment by devinivy** [comment]
I don't know how this works with nuxt, but it is possible to serve a redirect to joi.dev?

**Comment by Nargonath** [comment]
I haven't followed up with all the changes that occurred lately but I think we build this part based on a JSON datastructure and looping through it. We'd probably have to add a new behavior for that case, if not already done.

**Comment by Nargonath** [comment]
Got some more information about the problem. There's a link in hapi's API section of the website: https://hapi.dev/api/?v=20.0.0#-routeoptionsvalidateheaders. I think we need to update the hapi's API.md to remove that link.
