### ISSUE TITLE
Wither hawk?

### ISSUE THREAD

**Issue by djmitche** [hapijs/hapi.dev#416]
#### Support plan

* *is this issue currently blocking your project?* (yes/no): yes
* *is this issue affecting a production system?* (yes/no): yes

#### Context

* *node version*: 12
* *module version*: 8.0
* *environment* (e.g. node, browser, native): node + browser
* *used with* (e.g. hapi application, another framework, standalone, ...): express
* *any other relevant information*: none

#### How can we help?

[We](https://github.com/taskcluster/taskcluster) use Hawk for authentication.  https://www.npmjs.com/package/@hapi/hawk appears to be the latest release, but there is no changelog in the repository.  The README's changelog [links to nowhere](https://hapi.dev/family/hawk/changelog/).  I don't see the library listed under https://hapi.dev/module/?sort=name.  Has this been de-supported?  What changes occurred between v7 and v8?  What is the recommendation for users of this library?

**Comment by cjihrig** [comment]
> Has this been de-supported?

Yes, hawk is no longer supported. It now exists here: https://github.com/outmoded/hawk

**Comment by djmitche** [comment]
Thanks for the quick response!  We're working on taking ownership of the old repo and npm package :)

**Comment by kanongil** [comment]
It seems that your information is no longer current @cjihrig, as the repo has just been moved to the mozilla org: https://github.com/mozilla/hawk

**Comment by cjihrig** [comment]
It was current when I wrote the comment 😄. It sounds like @djmitche was able to take over the repo.

**Comment by djmitche** [comment]
That's correct.  Mozilla already hosts the Python and Rust implementations
and one of the many forks of the Golang implementation, so this seems a
reasonable move.
