### ISSUE TITLE
update proper link for gist code sample

### ISSUE THREAD

**Issue by rajrs** [hapijs/hapi.dev#418]
Url: https://hapi.dev/resources
section : Gists and code samples
issue: code sample repo links are not working it leads to 404 in github, Kindly update proper links or remove that section.

**Comment by lloydbenson** [comment]
@rajrs thanks for reporting this. I definitely can confirm we see the issue and I am looking into if we will remove the whole section or not. Thanks!

**Comment by lloydbenson** [comment]
This is resolved in PR #423.
