### ISSUE TITLE
Brigthen link text color when in dark mode

### ISSUE THREAD

**Issue by Nargonath** [hapijs/hapi.dev#478]
#### Support plan

* *is this issue currently blocking your project?* (yes/no):
* *is this issue affecting a production system?* (yes/no):

#### Context

* *node version*: 
* *module version with issue*: 
* *last module version without issue*: 
* *environment* (e.g. node, browser, native): 
* *used with* (e.g. hapi application, another framework, standalone, ...):
* *any other relevant information*:

#### What are you trying to achieve or the steps to reproduce?

I noticed that the text color of the button "previous"/"next" on the API page are not bright enough while in dark mode which makes them hard to read.

#### What was the result you got?

![image](https://user-images.githubusercontent.com/583657/123698772-cba44d00-d85e-11eb-9453-71b4dcca99c6.png)

#### What result did you expect?

A brighter color for the text of the link.

**Comment by hroseoc** [comment]
Hi! I've replicated the issue locally and I'm happy to try to fix it if you would like?

**Comment by devinivy** [comment]
@hroseoc that would be great and appreciated— go for it!
