### ISSUE TITLE
Clarify which node versions are supported for various packages

### ISSUE THREAD

**Issue by ariwbolton** [hapijs/hapi.dev#486]
#### Context

* *node version*: N/A
* *module version*: N/A

#### What are you trying to achieve or the steps to reproduce ?

The hapi.dev [module status page](https://hapi.dev/resources/status) shows that for the most recent version of all projects that only node 12 and 14 are supported, but it seems like many (all?) projects are tested against node 16 as well ([hapi](https://github.com/hapijs/hapi/blob/c7cfa2e0f9c1d4ba94b4715a5a268356f68294b3/.github/workflows/ci-module.yml#L15), [boom](https://github.com/hapijs/boom/blob/12e025c3e873e94cd9e5bfa0e7f4c891c94ea2f6/.github/workflows/ci-module.yml#L15), [iron](https://github.com/hapijs/iron/blob/d26fa2e06483a90ee81597815394155529cda798/.github/workflows/ci-module.yml#L15)), via testing against the "latest" node version. It even seems this support is also explicit: [here](https://github.com/hapijs/hapi/issues/4269#issuecomment-884034474)'s a post in which node 16 support is explicitly marked as supported (w.r.t. Hapi in particular).

So, my question is: does the Hapi ecosystem support node 16? (If so, is this just a bug in the docs?)

Thank you in advance!

**Comment by Nargonath** [comment]
I just updated the website:

<img width="733" alt="image" src="https://user-images.githubusercontent.com/583657/163400824-4c4aae00-428e-483f-983b-7c054b165c58.png">

You'll find the up to date support for now. We officially only support LTS versions even though we already start working on support from the odd versions.
