### ISSUE TITLE
Build script is broken after `hapijs/.github` changes

### ISSUE THREAD

**Issue by ChalkPE** [hapijs/hapi.dev#509]
#### Support plan

* *is this issue currently blocking your project?* (yes/no): yes
* *is this issue affecting a production system?* (yes/no): no

#### Context

* *node version*: `16.14.0`
* *module version with issue*: 6b782cdbd23019ed2b4d421154aa15efea3017de
* *last module version without issue*: 6b782cdbd23019ed2b4d421154aa15efea3017de
* *environment* (e.g. node, browser, native): `node`
* *used with* (e.g. hapi application, another framework, standalone, ...): `standalone`
* *any other relevant information*: https://github.com/hapijs/.github/commit/d08fdec0de2fafbade443ab7e716ade02b2324ab

#### What are you trying to achieve or the steps to reproduce?

- Every build script is producing same error, `~/static/lib/hapiInfo.json` was not found.
- This is caused by `assets/js/getModuleInfo` script, is also broken after recent changes of its external resource.
  - https://github.com/hapijs/.github/pull/21
  - `jobs.test.strategy.matrix.node` in `ci-module.yml` is now an expression (string), not an array of node versions.

#### What was the result you got?

`npm run dev`
```
> hapi.dev@1.0.0 dev
> cross-env NODE_ENV=development nodemon server/index.js --watch server

 ERROR  Failed to compile with 2 errors

This dependency was not found:

* ~/static/lib/hapiInfo.json in ./node_modules/babel-loader/lib??ref--2-0!./node_modules/vue-loader/lib??vue-loader-options!./pages/api.vue?vue&type=script&lang=js&

To install it, you can run: npm install --save ~/static/lib/hapiInfo.json

This relative module was not found:

* ../../static/lib/hapiInfo.json in ./node_modules/babel-loader/lib??ref--2-0!./node_modules/vue-loader/lib??vue-loader-options!./pages/resources/status.vue?vue&type=script&lang=js&
```

`npm run generate`:
```bash
> hapi.dev@1.0.0 generate
> node assets/js/getModuleInfo && nuxt generate

/Users/chalk/Documents/hapi.dev/assets/js/getModuleInfo.js:122
  let nodeGlobalVersions = Yaml.load(nodeYaml.data).jobs.test.strategy.matrix.node.reverse().filter(e=> e !== "*");
                                                                                   ^

TypeError: Yaml.load(...).jobs.test.strategy.matrix.node.reverse is not a function
    at getInfo (/Users/chalk/Documents/hapi.dev/assets/js/getModuleInfo.js:122:84)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
```

Adding `console.error(nodeYaml.data)` before `getModuleInfo.js:122`:
```yml
...
jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu, windows, macos]
        node: ${{ inputs.min-node-version == 14 && fromJSON('["*", "16", "14"]') || fromJSON('["16", "14", "12"]') }}
...
```

#### What result did you expect?

Required data is generated and page is built successfully.

**Comment by Nargonath** [comment]
Thank @ChalkPE for the detailed report. It seems we forgot that the website was leveraging the CI configuration to determine the supported node version and we didn't update it after the recent changes.

I expect though that Node 12 support will be dropped once it reaches EOL at the end of this month. I'm not sure we want to work on a fix for something that is likely to disappear in 2 weeks. Do you have an opinion on this @lloydbenson?
